# Generated by Django 5.0.6 on 2026-04-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=200)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("project", "Nouveau projet"),
                            ("quote", "Demande de devis"),
                            ("partnership", "Partenariat"),
                            ("support", "Support"),
                            ("other", "Autre"),
                        ],
                        default="project",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Demande de contact",
                "verbose_name_plural": "Demandes de contact",
                "ordering": ["-created_at"],
            },
        ),
    ]
