# Generated by Django 5.0.6 on 2026-04-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="Zsdevweb", max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "email",
                    models.EmailField(default="contact@zsdevweb.fr", max_length=254),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="France", max_length=100)),
                ("siret", models.CharField(blank=True, max_length=20)),
                ("vat_number", models.CharField(blank=True, max_length=30)),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True, default="Auto-entrepreneur", max_length=100
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="company/")),
                ("favicon", models.ImageField(blank=True, upload_to="company/")),
                ("social_linkedin", models.URLField(blank=True)),
                ("social_github", models.URLField(blank=True)),
                ("social_twitter", models.URLField(blank=True)),
                ("quote_validity_days", models.PositiveIntegerField(default=30)),
                ("quote_footer_text", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Paramètres société",
                "verbose_name_plural": "Paramètres société",
            },
        ),
    ]
