# Generated by Django 5.0.6 on 2026-04-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                (
                    "tech_stack",
                    models.JSONField(
                        default=list,
                        help_text="Liste de technologies (ex: ['Vue.js', 'Django', 'PostgreSQL'])",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="portfolio/")),
                (
                    "image_secondary",
                    models.ImageField(blank=True, upload_to="portfolio/"),
                ),
                ("url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Projet portfolio",
                "verbose_name_plural": "Projets portfolio",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_company", models.CharField(blank=True, max_length=200)),
                ("client_role", models.CharField(blank=True, max_length=200)),
                (
                    "client_avatar",
                    models.ImageField(blank=True, upload_to="testimonials/"),
                ),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to="portfolio.portfolioproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
