# Generated by Django 5.0.6 on 2026-04-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplexityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Multiplicateur appliqué au sous-total (ex: 1.3)",
                        max_digits=4,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Niveau de complexité",
                "verbose_name_plural": "Niveaux de complexité",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DesignOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price_supplement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant à ajouter au prix de base (HT)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Option de design",
                "verbose_name_plural": "Options de design",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom d'icône (ex: heroicons)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Catégorie de projet",
                "verbose_name_plural": "Catégories de projet",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("min_days", models.PositiveIntegerField(default=7)),
                ("max_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_types",
                        to="services_catalog.projectcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de projet",
                "verbose_name_plural": "Types de projet",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SupplementaryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Tarif mensuel récurrent (maintenance, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "recommended_for",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Types de projets pour lesquels cette option est recommandée",
                        related_name="recommended_options",
                        to="services_catalog.projecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option supplémentaire",
                "verbose_name_plural": "Options supplémentaires",
                "ordering": ["order", "name"],
            },
        ),
    ]
