# Generated by Django 5.0.6 on 2026-04-06 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        ("services_catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_email", models.EmailField(db_index=True, max_length=254)),
                ("client_phone", models.CharField(blank=True, max_length=20)),
                ("client_company", models.CharField(blank=True, max_length=200)),
                ("project_description", models.TextField(blank=True)),
                ("desired_deadline", models.DateField(blank=True, null=True)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "design_supplement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "complexity_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                (
                    "options_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "subtotal_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "vat_rate",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_ttc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "installment_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "installment_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "installment_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("viewed", "Consulté"),
                            ("accepted", "Accepté"),
                            ("rejected", "Refusé"),
                            ("expired", "Expiré"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "signature_token",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_file", models.FileField(blank=True, upload_to="quotes/%Y/%m/")),
                ("notes_internal", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "complexity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="services_catalog.complexitylevel",
                    ),
                ),
                (
                    "design_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="services_catalog.designoption",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="leads.lead",
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        blank=True, to="services_catalog.supplementaryoption"
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="services_catalog.projecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteEmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_to", models.EmailField(max_length=254)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Envoyé"), ("failed", "Échec")], max_length=20
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("message_id", models.CharField(blank=True, max_length=200)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="quotes.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log email devis",
                "verbose_name_plural": "Logs emails devis",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["status"], name="quotes_quot_status_bc6cd2_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["client_email"], name="quotes_quot_client__4a7a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["created_at"], name="quotes_quot_created_ede808_idx"
            ),
        ),
    ]
