# Generated by Django 5.0.6 on 2026-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
