# Generated by Django 5.0.6 on 2026-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_security_audit_fixes"),
        ("quotes", "0002_quote_pdf_generated_at"),
        ("services_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="signature_token",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=128
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["updated_at"], name="quotes_quot_updated_0a73c7_idx"
            ),
        ),
    ]
