# Generated by Django 5.0.6 on 2026-04-06 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("quotes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("briefing", "Briefing"),
                            ("design", "Design"),
                            ("development", "Développement"),
                            ("review", "Révision"),
                            ("delivered", "Livré"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="briefing",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("delivered_at", models.DateField(blank=True, null=True)),
                ("site_url", models.URLField(blank=True)),
                ("repo_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project",
                        to="quotes.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet client",
                "verbose_name_plural": "Projets clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contrat"),
                            ("mockup", "Maquette"),
                            ("deliverable", "Livrable"),
                            ("invoice", "Facture"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="client_docs/%Y/%m/")),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="client_portal.clientproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document projet",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("progress", "Avancement"),
                            ("milestone", "Jalon"),
                            ("delivery", "Livraison"),
                            ("feedback", "Demande de retour"),
                            ("info", "Information"),
                        ],
                        default="progress",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_visible_to_client", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="client_portal.clientproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mise à jour projet",
                "ordering": ["-created_at"],
            },
        ),
    ]
