# Generated by Django 5.0.6 on 2026-04-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
        ('quotes', '0002_quote_pdf_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='quote_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_document', to='quotes.quote'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='doc_type',
            field=models.CharField(choices=[('quote', 'Devis'), ('contract', 'Contrat'), ('mockup', 'Maquette'), ('deliverable', 'Livrable'), ('invoice', 'Facture'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
