# Generated by Django 5.0.6 on 2026-04-06 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services_catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("quote_wizard", "Wizard de devis"),
                            ("quick_estimate", "Estimation rapide"),
                            ("roi_calculator", "Calculateur ROI"),
                            ("audit_form", "Audit gratuit"),
                            ("contact_form", "Formulaire contact"),
                            ("simulator", "Simulateur de projet"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Score de qualification 0-100"
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("< 1000", "Moins de 1 000€"),
                            ("1000-3000", "1 000€ — 3 000€"),
                            ("3000-6000", "3 000€ — 6 000€"),
                            ("6000-15000", "6 000€ — 15 000€"),
                            ("> 15000", "Plus de 15 000€"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_converted", models.BooleanField(db_index=True, default=False)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="services_catalog.projecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_converted"], name="leads_lead_is_conv_bd9464_idx"
                    ),
                    models.Index(fields=["score"], name="leads_lead_score_016ea8_idx"),
                ],
            },
        ),
    ]
