# Generated by Django 5.0.6 on 2026-04-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("site_url", models.URLField()),
                (
                    "current_issues",
                    models.TextField(
                        blank=True, help_text="Problèmes actuels identifiés"
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        default=list, help_text="Liste d'objectifs sélectionnés"
                    ),
                ),
                ("budget_range", models.CharField(blank=True, max_length=50)),
                ("timeline", models.CharField(blank=True, max_length=100)),
                ("additional_info", models.TextField(blank=True)),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Demande d'audit",
                "verbose_name_plural": "Demandes d'audit",
                "ordering": ["-created_at"],
            },
        ),
    ]
